products = [
  {
    id: "1",
    name: "Nike Air Max 95 OG 'Bright Mandarin'",
    info: "Big. Bold. Bounce. To celebrate 30 years of the iconic silhouette, the Air Max family is welcoming back the 'Big Bubble' edition of the 95. With a design that stays true to the original, this iteration stacks the upper with rippling layers of synthetic leather and airy mesh that gradually fade from black to white. Pops of Bright Mandarin accentuate the lace loops, branding and Air units. Elevate your style with a little more Air and enjoy the future of your Air Max journey.",
    brand: "Nike",
    price: 283,
    category: "shoes",
    gender: "male",
    img: "/img/men/1.jpeg",
  },
  {
    id: "2",
    name: "Nike Shox Ride 2 'Metallic Platinum'",
    info: "A modern classic, this Nike Shox Ride 2 offers outstanding responsive cushioning with four columns of support under its heel and Max Air technology in the forefoot. And the breathable textile and genuine leather upper is comfortable and durable.",
    brand: "Nike",
    price: 150,
    category: "footwear",
    gender: "male",
    img: "/img/men/2.jpeg",
  },
  {
    id: "3",
    name: "Nike Air Force 1 Low Retro 'Escape'",
    info: "This 2002 edition of the Air Force 1 is back. It comes wrapped in full-grain leather and signature color blocking for a luxe look that's easy to style. And of course, Nike Air cushioning keeps it true to the original.",
    brand: "Nike",
    price: 165,
    category: "footwear",
    gender: "male",
    img: "/img/men/3.jpeg",
  },
  {
    id: "4",
    name: "SKEPTA x PUMA Skope Mid",
    info: "”No hype, no adlibs” - just the undisputed King of Grime. Skepta’s creative partnership with Puma continues with the Forever Mid Sneakers, a rugged reworking of the OG low silhouette. Straying from the beaten track, they’re styled with sturdy leather, a heightened ankle and hiking boot-style laces giving the BBK MC’s signature tech-luxe style a trail-ready makeover. The chunky Forever sole, complete with a high-shine chrome insert, provides sturdy support and an eye-catching finish underfoot.",
    brand: "Puma",
    price: 176,
    category: "footwear",
    gender: "male",
    img: "/img/men/4.jpeg",
  },
  {
    id: "5",
    name: "Puma Speedcat Leather",
    info: "The iconic Speedcat is reborn for the streets. Premium leather and bold design fuse motorsport heritage with modern style. Painted and debossed branding provides unmistakeable attitude underfoot, while an OrthoLite® sockliner ensures all-day comfort for those always on the go.",
    brand: "Puma",
    price: 165,
    category: "footwear",
    gender: "male",
    img: "/img/men/5.jpeg",
  },
  {
    id: "6",
    name: "Reebok Club C Bulc 'Dark Green'",
    info: "Mashing up bold Y2K style and Reebok DNA, these shoes stay true to their inspiration with bold colour choices and a contrasting outsole. Everything is bigger on these sneakers, from the blown-out upper to the fat laces. The tongue label opens at the top to create a pocket.",
    brand: "Reebok",
    price: 140,
    category: "footwear",
    gender: "male",
    img: "/img/men/6.jpeg",
  },
  {
    id: "7",
    name: "New Balance Women's 530",
    info: "A stylish, ultra-cushioned sneaker with classic design aesthetics.",
    brand: "New Balance",
    price: 118,
    category: "footwear",
    gender: "female",
    img: "/img/women/7.jpeg",
  },
  {
    id: "8",
    name: "New Balance Women's 550 V1 'Premium Pack'",
    info: "The original 550 debuted in 1989 and made its mark on basketball courts from coast to coast. After its initial run, the 550 was filed away in the archives, before being reintroduced in limited-edition releases in late 2020, and returned to the full-time lineup in 2021, quickly becoming a global fashion favorite. The 550’s low top, streamlined silhouette offers a clean take on the heavy-duty designs of the late ‘80s, while the dependable leather, synthetic, and mesh upper construction is a classic look in any era.",
    brand: "New Balance",
    price: 95,
    category: "footwear",
    gender: "female",
    img: "/img/women/8.jpeg",
  },
  {
    id: "9",
    name: "Adidas Women's Campus 00's",
    info: "These adidas shoes playfully reinterpret an icon, doubling up on the tongue and thickening the laces for a bold, impactful look. The smooth leather upper and textile lining keep you comfortable as you make a mark with your style. With their '00s attitude and modern details, these sneakers let you express your individuality.",
    brand: "Adidas",
    price: 103,
    category: "footwear",
    gender: "female",
    img: "/img/women/9.jpeg",
  },
  {
    id: "10",
    name: "Adidas Women's Gazelle Stack",
    info: "Whether you're exploring the city or hitting your usual spots, the Gazelle Stack Shoes keep your style elevated. Once an iconic training shoe, now a bold fashion statement, the Gazelle Stack features layers of moulded EVA in the midsole for an ultra-high platform. A smooth leather upper, suede accents and semi-translucent foxing tape add retro appeal. Step into a piece of adidas Originals history and make a memorable entrance wherever the day takes you.",
    brand: "Adidas",
    price: 87,
    category: "footwear",
    gender: "female",
    img: "/img/women/11.jpeg",
  },
  {
    id: "11",
    name: "Puma V-S1 Metallic",
    info: "In the early ‘00s, the PUMA V1.08 was one of the most ground-breaking football boots on the pitch. Today, they’re back to dominate once again, only this time it's off the pitch. The genre-defying ethos of the V1.08 has been injected into the V-S1. By transforming the boot into a sneaker, the V-S1 is a singular vision of modern style and Y2K cyberism, with ultra-clean design lines and metallic accents.",
    brand: "Puma",
    price: 112,
    category: "footwear",
    gender: "female",
    img: "/img/women/11.jpeg",
  },
  {
    id: "12",
    name: "New Balance Women's 550 'Evolve Pack'",
    info: "The original 550 debuted in 1989 and made its mark on basketball courts from coast to coast. After its initial run, the 550 was filed away in the archives, before being reintroduced in limited-edition releases in late 2020, and returned to the full-time lineup in 2021, quickly becoming a global fashion favourite. The 550’s low-top, streamlined silhouette offers a clean take on the heavy-duty designs of the late ‘80s, while the dependable leather upper construction is a classic look in any era.",
    brand: "New Balance",
    price: 87,
    category: "footwear",
    gender: "female",
    img: "/img/women/12.jpeg",
  },
  {
    id: "13",
    name: "Nike Sportswear Tech Fleece Re-Imagined Loose Fit Open Hem Track Pants",
    info: "These tailored trousers are everything you love about our smooth, comfy Tech Fleece in a roomy, inspired design. Traditional tailored details like pleating down the front and zip fly front closure are combined with the drawcord waistband and soft fleece fabric for a mix-and-mash look where old meets new. Our premium, smooth-on-both-sides fleece feels warmer and softer than ever while keeping the same lightweight build you love. Pair them up with our Tech Fleece Re-imagined Shacket and escape into the future of comfort.",
    brand: "Nike",
    price: 215,
    category: "apparel",
    gender: "male",
    img: "/img/men/13.jpeg",
  },
  {
    id: "14",
    name: "Nike Sportswear Tee",
    info: "Clean and classic, this lightweight cotton tee is designed to feel relaxed through the body for casual comfort and easy layering. Fresh Nike graphics keep your style on point and remind you that everything's better with Air.",
    brand: "Nike",
    price: 56,
    category: "apparel",
    gender: "male",
    img: "/img/men/14.jpeg",
  },
  {
    id: "15",
    name: "Tobe x Reebok Zip Pants",
    info: "Crafted from premium linen, these woven pants feature zip-off legs, allowing for an effortless transition from full-length to shorts, adapting to your needs with ease. The elastic waistband, complemented by side drawcords, ensures a personalized fit, while padded panels add both comfort and a distinctive aesthetic.",
    brand: "Reebok",
    price: 98,
    category: "apparel",
    gender: "male",
    img: "/img/men/15.jpeg",
  },
  {
    id: "16",
    name: "Tobe x Reebok Hoodie",
    info: "This Reebok hoodie is designed with actor, rapper and singer Tobe Nwigwe. Inspired by Tobe's roots in football and the preseason, it blends classic design with intricate details. The color Mint symbolizes things falling into place as they are Mint to be. Premium fleece, applique, and embroidered accents elevate this look.",
    brand: "Reebok",
    price: 134,
    category: "apparel",
    gender: "male",
    img: "/img/men/16.jpeg",
  },
  {
    id: "17",
    name: "New Balance Coaches Twill Jacket",
    info: "Presenting the New Balance Coaches Twill Jacket - Dockside - MO51510_DOK.This twill jacket is designed for everyday wear.",
    brand: "New Balance",
    price: 112,
    category: "apparel",
    gender: "male",
    img: "/img/men/17.jpeg",
  },
  {
    id: "18",
    name: "Puma Track Jacket 'Players Lane'",
    info: "The track jacket by Puma with an allover stripe pattern. Mock neck jacket with a zip closure front and ribbed knit trims.",
    brand: "Puma",
    price: 156,
    category: "apparel",
    gender: "male",
    img: "/img/men/18.jpeg",
  },
  {
    id: "19",
    name: "Song for the Mute x Adidas Woven Jacket",
    info: "This adidas jacket is a work of art you can wear. It's part of a collection with Song for the Mute an Australian label celebrated for its use of luxury fabrics and impeccable craftsmanship. Brought to life with a premium twill fabric, this piece has a loose, easygoing fit with a versatile two-way zipper and a stand-up collar. Ribbed cuffs keep the sleeves from slipping. This jacket was made using UNITEFIT an all-gender fit system that was created with a spectrum of sizes, genders and forms in mind. This product is made with 100% recycled materials. By reusing materials that have already been created, we help to reduce waste and our reliance on finite resources and reduce the footprint of the products we make.",
    brand: "Adidas",
    price: 275,
    category: "apparel",
    gender: "female",
    img: "/img/women/19.jpeg",
  },
  {
    id: "20",
    name: "Song for the Mute x Adidas Woven Pants",
    info: "Take your style cues from the Australian fashion label Song for the Mute. These adidas pants are cut for a loose shape that creates a casual, carefree vibe, with a stretchy, adjustable waistband and pockets for the essentials. The twill build adds texture and depth, while 3-Stripes down the front of the legs does the unexpected with the signature element. Wear them when comfort is key but you don't want to compromise on style. These pants were made using UNITEFIT an all-gender fit system that was created with a spectrum of sizes, genders and forms in mind. This product is made with 100% recycled materials. By reusing materials that have already been created, we help to reduce waste and our reliance on finite resources and reduce the footprint of the products we make.",
    brand: "Adidas",
    price: 148,
    category: "apparel",
    gender: "female",
    img: "/img/women/20.jpeg",
  },
  {
    id: "21",
    name: "Nike Women's Sportswear Essential Mid-Rise Oversized Woven Joggers",
    info: "With both a water-repellent finish and built-in UV protection, these oversized trousers are ready come rain or shine. Their lightweight woven fabric is partially lined with sweat-wicking mesh to help keep you cool and dry.",
    brand: "Nike",
    price: 135,
    category: "apparel",
    gender: "female",
    img: "/img/women/21.jpeg",
  },
  {
    id: "22",
    name: "FUTURA x Nike Women's Sportswear Breaking Windrunner Jacket",
    info: "Bring your body, mind and soul to the world stage in this roomy jacket. A common theme in New York artist FUTURA's work, the spinning atom graphics symbolize perpetual motion. Sweat-wicking tech and lightweight woven fabric help keep you comfortable for the physics-defying moves you make in the cypher.",
    brand: "Nike",
    price: 193,
    category: "apparel",
    gender: "female",
    img: "/img/women/22.jpeg",
  },
  {
    id: "23",
    name: "New Balance Women's Varsity Tee",
    info: "A classic, heritage-inspired t-shirt designed for effortless style.",
    brand: "New balance",
    price: 62,
    category: "apparel",
    gender: "female",
    img: "/img/women/23.jpeg",
  },
  {
    id: "24",
    name: "New Balance Women's Athletics French Terry Full-Zip Hoodie 'Grey Day'",
    info: "This versatile full-zip hoodie is designed for everyday wear.",
    brand: "New Balance",
    price: 106,
    category: "apparel",
    gender: "female",
    img: "/img/women/24.jpeg",
  },
  {
    id: "25",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
  {
    id: "26",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
  {
    id: "27",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
  {
    id: "28",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
  {
    id: "29",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
  {
    id: "30",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
  {
    id: "31",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
  {
    id: "32",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
  {
    id: "33",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
  {
    id: "34",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
  {
    id: "35",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
  {
    id: "36",
    name: "",
    info: "",
    brand: "",
    price: 1,
    category: "",
    gender: "",
    img: "",
  },
];
